# Generated by Django 4.0.2 on 2022-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
